### ISSUE TITLE
Fix collator (undying/adder) cmd args

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1245]
Followup from https://github.com/paritytech/polkadot/pull/7617#issuecomment-1678536346, we should not use `--validator` in those collators cmd.

**Comment by skunert** [comment]
I think maybe zombienet should move away from using `--validator` at all for collators. There is the `--collator` flag for cumulus-based nodes that indicates that the node should produce blocks.

The validator term is confusing here since it mostly means relay chain nodes.

The CLI in cumulus is set up to change any given `--validator` flag into `--collator`, so there it is impossible to even start the internal relay chain node in validator mode.

So maybe the solution is to use `--collator` for cumulus-based nodes and no default for non-cumulus based nodes. Maybe we should even move away from supplying these default args (except for the stuff zombienet needs to work of course), its kind of hard to reason about them.

**Comment by pepoviola** [comment]
Hi @skunert, thanks for your help and feedback. Yes, I agree that we should move away from using `--validator` in collators. I'm already working on the fix.


>Maybe we should even move away from supplying these default args (except for the stuff zombienet needs to work of course), its kind of hard to reason about them.

Which default args you mean? We are currently working on the `v2` and we want to change the way we handle `defaults`.

Again, thanks for your help 👍

**Comment by skunert** [comment]
I meant that validator = true is the default for zombienet.

**Comment by pepoviola** [comment]
> I meant that validator = true is the default for zombienet.

Ah, we can iterate over that for the new version and try to achieve the best trade-off between explicit set and default value.
Thanks!
