### ISSUE TITLE
Truncated log files

### ISSUE THREAD

**Issue by mrcnski** [paritytech/zombienet#1611]
In table mode there is some output that gets truncated and is not usable.

![Screenshot 2023-12-21 at 10 04 22](https://github.com/paritytech/zombienet/assets/6035856/6ddad009-21fb-4ac2-b350-2573103cfee0)
![Screenshot 2023-12-21 at 10 04 53](https://github.com/paritytech/zombienet/assets/6035856/ff1aad32-dbe2-4860-a803-04a32948f7c8)

I presume the table cells have a limit width. Perhaps the output could be wrapped onto the following line - then it can be reconstructed with a series of consecutive copy/paste maneouvers.

**Comment by pepoviola** [comment]
Hi @mrcnski, thanks for your feedback. We have the `text` output option as a better option for copy/paste.

```bash
❯ node packages/cli/dist/cli.js -l text  -p native spawn ../support-files/1616.toml
```

<img width="1479" alt="image" src="https://github.com/paritytech/zombienet/assets/363911/6acd0868-1451-42f8-a37b-9b7063a97a49">


I will close this one since we explore in the past with wrapping in the `table` output but we conclude that having a `text` output was better. Thanks again for your feedback!!

**Comment by mrcnski** [comment]
Thanks! I forgot to mention the `-l` option: I tried it, but there was something missing from the output. If I see the problem again I'll raise a separate issue. 👍🏻
