### ISSUE TITLE
Modifying genesis config of parachain can fail with  `⚠ Bad Genesis Configuration` for a key that isn't already present

### ISSUE THREAD

**Issue by alindima** [paritytech/zombienet#1614]
Trying to modify the genesis config of a parachain in toml for a key not already existent in the genesis `patch` section fails with: ` ⚠ Bad Genesis Configuration`.

For example, the glutton_westend runtime does not add the "glutton" pallet config to the chainspec "genesis.runtimeGenesis.patch" section.

Adding this in the network spec will fail:
```
[parachains.genesis.runtimeGenesis.patch.glutton]
  compute = "50000000"
  storage = "131000000"
  trashDataCount = 5120
```

**Comment by pepoviola** [comment]
Hi @alindima, thanks for reporting :). 
Zombienet works by *only* allow to override existing keys in the genesis, but with the changes on the machinery to generate the `spec` we may need to change that assumption. @michalkucharczyk there is a way to know if the key is valid or not?  Since if we allow to `add` new keys to the genesis config I would like to have some way to validate those. Also, I think if we don't validate those and the keys are wrong the `raw` generating will fail but I have to confirm that behavior.

Thanks!

**Comment by michalkucharczyk** [comment]
To validate the patch you need to generate raw storage. Generating raw storage from genesis config (full or parch) json is the only way to validate if given json representation is valid. This process deserializes RuntimeGenesisConfig from json blob.

The patch can contain any keys as long as they are valid from runtime perspective (precisely speaking assuming that all struct have deny_uknown_fields serde option).

Could you share toml file?

**Comment by michalkucharczyk** [comment]
Also cross-check question - what version of zombienet are you using?

**Comment by michalkucharczyk** [comment]
> Also, I think if we don't validate those and the keys are wrong the `raw` generating will fail but I have to confirm that behavior.

That is correct.

**Comment by pepoviola** [comment]
Thanks for your feedback @michalkucharczyk, I will change the logic to allow to add `keys` as part of the overriding proces.
Thx!

**Comment by pepoviola** [comment]
Hi @alindima, this fix is already included in the latest version. 
https://github.com/paritytech/zombienet/releases/tag/v1.3.89
Thx!

**Comment by alindima** [comment]
Thanks! I was away for the holidays but good to see this landed 👍🏻
