### ISSUE TITLE
Zombienet won't allow whitespaces in collator names

### ISSUE THREAD

**Issue by ggwpez** [paritytech/zombienet#1659]
SE [issue](https://substrate.stackexchange.com/questions/10776) mentions that names should be passed in quotes like `--name "name"` instead of `--name name`.  
Using zombienet v1.89 i did not verify myself, just opening this so we can close the other.

**Comment by wirednkod** [comment]
Thank you @ggwpez 
All the configuration options are actually translating into a linux `cmd` (e.g. `--name someting-something`) so having spaces will mean that after 1st word ,the 2nd word will be some other arg.
I am not sure if this should be fixed by mentioning it in the documentation, or adding a trim/replace function to convert the spaced-name to (lets say) dashed-name.
What do you think @pepoviola ?

**Comment by pepoviola** [comment]
Hey @wirednkod / @ggwpez, thanks for report this issue. We are using the `name` of the node in several places and we should check if having a whitespace there doesn't break anything more. I think we should explore if is possible to support naming with whitespace, and if generate more troubles we can move to `replace` whitespaces with dashes.

Thx!

**Comment by wirednkod** [comment]
@pepoviola I think the best way to ensure that there is nothing breaking is a simple replacement of spaces -> dashes. It does not really make much sense to me, to have spaces into the name to be honest 🤷🏽

**Comment by pepoviola** [comment]
> @pepoviola I think the best way to ensure that there is nothing breaking is a simple replacement of spaces -> dashes. It does not really make much sense to me, to have spaces into the name to be honest 🤷🏽

Ok but we should make this transformation clear in the docs since the users should know that the name of the node will be changed replacing spaces with dashes. Thanks!!
