### ISSUE TITLE
[feat] Add `logs` attribute

### ISSUE THREAD

**Issue by NachoPal** [paritytech/zombienet#264]
Add `logs` attribute to `relaychain.nodes` and `parachains.collators` to be able to override the default path where logs are saved.

**Comment by pepoviola** [comment]
Hi @NachoPal, just to clarify this will only works for `native` provider and we should truncate the old log if exists.
If you are agree I can implement those changes.
Thanks!

**Comment by NachoPal** [comment]
Hi, I am fine if it can only works for native. I don't understand though what you mean by "we should truncate the old log if exists."

**Comment by pepoviola** [comment]
> Hi, I am fine if it can only works for native. I don't understand though what you mean by "we should truncate the old log if exists."

This means that if you set the log to a `file` that already exist we will wipe that file with the new logs.

Thanks!

**Comment by NachoPal** [comment]
> > Hi, I am fine if it can only works for native. I don't understand though what you mean by "we should truncate the old log if exists."
> 
> This means that if you set the log to a `file` that already exist we will wipe that file with the new logs.
> 
> Thanks!

That is totally fine and expected behaviour

**Comment by skunert** [comment]
I came across this issue recently and also would like to customize log output folder for native provider. 
Just another idea one could handle this:
- specify `ZOMBIENET_LOG_DIR` env variable on local machine (or cli)
- In this directory just create a new folder per run, something like `test_name_2022_10_13T08_45_31`, inside all logs and artifacts of that run instead of the tmp folder

The benefits I see here is that no logs are being wiped on a new run. The workflow would be enhanced by just starting a zombienet test and waiting for the new folder to appear in specified directory.
But I see that its more work  of course.

**Comment by pepoviola** [comment]
Hi @skunert, sounds good. I think we can add a `working-dir` parameter to the `cli` and use as main directory for all the artifacts that zombienet create (and logs/databases).

ping @wirednkod can we add the `--working-dir` option to the cli?

Thanks!
