### ISSUE TITLE
Using Podman on MacOS is not supported

### ISSUE THREAD

**Issue by sacha-l** [paritytech/zombienet#431]
Opening this issue for the sake of updating the docs accordingly.

**Comment by wirednkod** [comment]
Thank you @sacha-l . Just a note that podman is supposed to be a Docker replacement and is meant mainly for linux (if that helps)

**Comment by wirednkod** [comment]
I parsed through podman documentation and it seems that MacOS [is actually supported](https://podman.io/getting-started/installation#macos). I will continue with all the appropriate installation and get back to you on this. Thank you

**Comment by pepoviola** [comment]
@sacha-l / @wirednkod to clarify, `podman` is supported in MacOS _but_ through an internal `vm` and the code for the provider (in zombienet) support podman running native (the way that works on linux). 

The issue is related mostly to `paths` and directories used by store configuration (chain-spec) and the `data` directory, I think we need to make a `note` that can only be used in `linux` at the moment.

Thanks!
