### ISSUE TITLE
[bug] race condition between fileserver and pod

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#700]
For some configurations we have a race condition between the first pod and the fileserver. We should add `wait until ready` for the fileserver to ensure is ready when the first pod is starting.

see: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2314818

cc: @michalkucharczyk

**Comment by davxy** [comment]
@pepoviola The [comment](https://github.com/paritytech/substrate/pull/13078#issuecomment-1405496729) for an outstanding substrate PR says that tests are not passing due to this.

Indeed I saw a test failing repeatedly there, but now is green. Is this issue something that manifests sporadically? Is ok to merge our PR or we have to wait for this issue to be solved?

**Comment by pepoviola** [comment]
> @pepoviola The [comment](https://github.com/paritytech/substrate/pull/13078#issuecomment-1405496729) for an outstanding substrate PR says that tests are not passing due to this.
> 
> Indeed I saw a test failing repeatedly there, but now is green. Is this issue something that manifests sporadically? Is ok to merge our PR or we have to wait for this issue to be solved?

Hi @davxy, this race condition happens sporadically (and under heavy load in our cluster). Is safe to merge the pr in substrate :)

Thanks!!
