### ISSUE TITLE
setup giving error on Linux

### ISSUE THREAD

**Issue by DanEscher98** [paritytech/zombienet#707]
Testing on native `Fedora 37`:

Downloading the latests version from Github releases:
```bash
$ zombienet setup polkadot polkadot-parachain
# UnhandledRejection:      Error: `latestPolkadotReleaseURL` error: AxiosError: Request failed with status code 403
```
After follow the instructions to run the `javascript` cli:
```bash
$ cd zombienet/javascript/
$ npm install; npm run build
$ cd packages/cli/
$ node dist/cli.js setup polkadot polkadot-parachain
# UnhandledRejection:      Error: `latestPolkadotReleaseURL` error: AxiosError: Request failed with status code 403
```

**Comment by wirednkod** [comment]
Thank you Danyiel. This is a 403 error (no permission error). Im not sure why you got that - but once we tried together in you linux OS, it seemed to work fine. I will make a more generic error message that will specifically include the status and message of the error, in order to be more clear in the future.
