### ISSUE TITLE
Add possibility to pass arguments to zndsl

### ISSUE THREAD

**Issue by bobo-k2** [paritytech/zombienet#947]
### Is your feature request related to a problem? Please describe.

I would like to have a possibility to pass additional arguments to zndsl file which will be further passed to test scripts, so I can pass some continuous integration variables to tests scripts.

### Describe the solution you'd like

It would be great if I can execute something like:

`./zombienet-macos test -p native ./e2e.zndsl --args:input1,input2`

and inside my `e2e.znsdl` file write something like:

`astar: js-script ./start-playwright.js with {{args}}`

### Describe alternatives you've considered

Didn't try any alternative approach yet.

**Comment by pepoviola** [comment]
Hi @bobo-k2, thanks for your feedback. Currently you can use `env vars` to get the same behavior. For example, you can have your test definition (`.zndsl`) like this:

```
astar: js-script ./start-playwright.js with {{E2E_ARGS}}
```

And then run zombienet with

```bash
E2E_ARGS="nput1,input2" ./zombienet-macos test -p native ./e2e.zndsl
```

And zombienet will grab the env vars and merge them with you test file, since we use `nunjucks` templates in both network definition and test definition, and we make all the replacements before parsing them.

Let me know if you have questions, 
Thanks!!
